package export

import (
	"bytes"
	"fmt"
	"html"
	"strings"
)

// BuildHTML returns a standalone HTML document with embedded CSS, suitable
// for saving locally and opening offline. Per IDEA.md "Export Formats".
func BuildHTML(doc *Document) ([]byte, error) {
	var b bytes.Buffer
	fmt.Fprintf(&b, `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>%s</title>
  <meta name="generator" content="casman export">
  <style>
%s
  </style>
</head>
<body>
<header>
  <h1>%s</h1>
  %s
</header>
<main>
`,
		html.EscapeString(doc.Title),
		standaloneCSS,
		html.EscapeString(doc.Title),
		subtitleHTML(doc.Subtitle),
	)

	for _, page := range doc.Pages {
		fmt.Fprintf(&b, `<section class="manpage">
  <h2 id="%s-%s">%s(%s)</h2>
  <p class="meta"><em>%s</em> &mdash; %s</p>
`,
			html.EscapeString(strings.ToLower(page.Name)),
			html.EscapeString(page.Section),
			html.EscapeString(page.Name),
			html.EscapeString(page.Section),
			html.EscapeString(page.Title),
			html.EscapeString(page.Platform),
		)
		if page.Synopsis != "" {
			fmt.Fprintf(&b, "  <h3>Synopsis</h3><pre>%s</pre>\n",
				html.EscapeString(page.Synopsis))
		}
		body := page.ContentHTML
		if body == "" {
			body = "<pre>" + html.EscapeString(page.ContentText) + "</pre>"
		}
		b.WriteString(body)
		b.WriteString("\n</section>\n")
	}

	b.WriteString(`</main>
<footer><p>Generated by casman</p></footer>
</body>
</html>
`)
	return b.Bytes(), nil
}

func subtitleHTML(s string) string {
	if s == "" {
		return ""
	}
	return "<p>" + html.EscapeString(s) + "</p>"
}

const standaloneCSS = `
body { font-family: ui-sans-serif, system-ui, -apple-system, sans-serif;
       max-width: 880px; margin: 2rem auto; padding: 0 1rem;
       color: #1f2330; background: #ffffff; line-height: 1.6; }
header { border-bottom: 2px solid #d0d3dc; padding-bottom: 1rem; margin-bottom: 2rem; }
h1 { color: #d63a55; margin: 0 0 0.5rem; }
h2 { border-bottom: 1px solid #d0d3dc; padding-bottom: 0.4rem; margin-top: 2.5rem; }
h3 { margin-top: 1.5rem; }
section.manpage { margin-bottom: 3rem; page-break-after: always; }
section.manpage:last-child { page-break-after: auto; }
.meta { color: #5b6273; }
pre { font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
      background: #f1f3f7; padding: 0.75rem 1rem; border-radius: 4px;
      overflow-x: auto; white-space: pre-wrap; }
code { background: #f1f3f7; padding: 0.1rem 0.3rem; border-radius: 3px; }
footer { color: #5b6273; font-size: 0.85rem; margin-top: 3rem;
         border-top: 1px solid #d0d3dc; padding-top: 1rem; text-align: center; }
@media print {
  body { color: #000; }
  section.manpage { page-break-after: always; }
  pre { background: #f5f5f5; }
}
`
